web:
  build: .
  entrypoint: java
  command: $JVM_OPTS -cp target/thelounge-0.1.0.jar clojure.main -m lounge.api
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  links:
    - db:lounge_db
db:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - /data/db
  command: --smallfiles --rest
